"""Validated models and analyses for the Roulette Analytics Lab."""

from .bets import (
    BetKind,
    BetSpec,
    EnPrisonState,
    SpecialRule,
    expected_net_return,
    house_edge,
    kelly_fraction,
    make_standard_bet,
)
from .bankroll import (
    BankrollConfig,
    BankrollSimulation,
    RiskSummary,
    StrategyKind,
    simulate_bankroll,
    summarize_bankroll,
)
from .wheels import (
    Pocket,
    WheelKind,
    WheelSpec,
    make_biased_wheel,
    make_fair_wheel,
    validate_probability_vector,
    wheel_with_single_pocket_probability,
)
from .io import SpinDataset, read_spin_csv, write_spin_csv
from .statistics import (
    FairnessResult,
    MaxCountResult,
    PosteriorEstimate,
    PowerEstimate,
    chi_square_fairness,
    dirichlet_posterior,
    max_count_test,
    monte_carlo_global_pvalue,
    split_spin_history,
    estimate_detection_power,
    simulate_spin_counts,
)
from .analysis import AnalysisBundle, AnalysisConfig, run_full_analysis
from .sequential import (
    CUSUMResult,
    SequentialEvidence,
    cusum_change_detection,
    likelihood_ratio_path,
)
from .decision import PosteriorEdgeSummary, posterior_edge_summary
from .risk import build_risk_frontier, conditional_value_at_risk

__all__ = [
    "BetKind",
    "BetSpec",
    "AnalysisBundle",
    "AnalysisConfig",
    "BankrollConfig",
    "BankrollSimulation",
    "CUSUMResult",
    "EnPrisonState",
    "FairnessResult",
    "MaxCountResult",
    "Pocket",
    "PosteriorEdgeSummary",
    "PosteriorEstimate",
    "PowerEstimate",
    "RiskSummary",
    "SequentialEvidence",
    "SpecialRule",
    "StrategyKind",
    "WheelKind",
    "WheelSpec",
    "SpinDataset",
    "expected_net_return",
    "build_risk_frontier",
    "conditional_value_at_risk",
    "house_edge",
    "kelly_fraction",
    "likelihood_ratio_path",
    "chi_square_fairness",
    "cusum_change_detection",
    "dirichlet_posterior",
    "make_biased_wheel",
    "make_fair_wheel",
    "make_standard_bet",
    "max_count_test",
    "monte_carlo_global_pvalue",
    "estimate_detection_power",
    "posterior_edge_summary",
    "read_spin_csv",
    "run_full_analysis",
    "simulate_spin_counts",
    "simulate_bankroll",
    "split_spin_history",
    "summarize_bankroll",
    "validate_probability_vector",
    "wheel_with_single_pocket_probability",
    "write_spin_csv",
]
