[theme]
base = "light"
primaryColor = "#D32842"
backgroundColor = "#F7F7F4"
secondaryBackgroundColor = "#EEEEE9"
textColor = "#171816"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
